export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_ALL_TIKET_PENDING="GET_ALL_TIKET_PENDING"
export const GET_ALL_TIKET_SUCCESS="GET_ALL_TIKET_SUCCESS"
export const GET_ALL_TIKET_FAIL="GET_ALL_TIKET_FAIL"

export const GET_ALL_TYPE_PENDING="GET_ALL_TYPE_PENDING"
export const GET_ALL_TYPE_SUCCESS="GET_ALL_TYPE_SUCCESS"
export const GET_ALL_TYPE_FAIL="GET_ALL_TYPE_FAIL"

export const CREATE_TICKET_PENDING="CREATE_TICKET_PENDING"
export const CREATE_TICKET_SUCCESS="CREATE_TICKET_SUCCESS"
export const CREATE_TICKET_FAIL="CREATE_TICKET_FAIL"