export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_ALL_TIKET_PENDING="GET_ALL_TIKET_PENDING"
export const GET_ALL_TIKET_SUCCESS="GET_ALL_TIKET_SUCCESS"
export const GET_ALL_TIKET_FAIL="GET_ALL_TIKET_FAIL"